fout = open('full_table.txt','w')
print("#this table generated by script 'full_table.py'",file=fout)
print('Species','taxonomy','A','T','G','C','X','FULL_GENOME',sep='\t',file=fout)
import re
cercatrova = 'ORIGIN      '
basta = '//'
switch = 0;
switch2 = 0
word='  ORGANISM  '
word2='REFERENCE   1'
with open('data_base.gb','r') as file:
    for line in file:
        if word in line:  #вытаскиваем название, очищаем от шлака
            a = (line.replace(' ','_')[12:len(line)])
            b=re.sub('[-.,]','',a)
            c=re.sub('\n','',b)  #запоминаем и выводим в конце
            switch = 1   
            listsys = [] 
        if switch == 1:  #вытаскиваем систематику
            d = line.replace(';','_')
            e=re.sub('\n','',d)
            ee=re.sub('[ -.,]','',e)
            listsys.append(ee)
        if word2 in line:
            switch = 0
            listsys.pop(0)
            listsys.pop()
            strsys=''.join(listsys) #запоминаем, выводим в конце
        if cercatrova in line:   #вытаскиваем геномку
            switch2 = 1
            f = [] 
        if switch2 == 1:
            g=re.sub('[ /]','',line)
            h = re.sub(r'\d', r'', g)
            l = h.upper()
            l1=re.sub('\n','',l)
            l2=re.sub('[^ATGC]','X',l1)
            f.append(l2)
        if basta in line:
            switch2 = 0
            f.pop(0)
            f.pop()
            m=(''.join(f))
            numA=m.count('A')
            numT=m.count('T')
            numG=m.count('G')
            numC=m.count('C')
            numX=m.count('X')
            print(c, strsys, numA, numT, numG, numC, numX, m, sep='\t', file=fout)
